
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Teo
 */
public class Taixe extends javax.swing.JInternalFrame {

    /**
     * Creates new form Taixe
     */
    private Connect_Var cnDB;
    private DefaultTableModel mtable;
    private DefaultComboBoxModel model;
    private ResultSet rs;
    private ResultSetMetaData rsmd;
    private Vector vt;
    private int n = -1,edit;
    private String MaTX, MaCN, TenTX,sdt,imagepath;
    public Taixe() {
        initComponents();
        Initcbbox();
        InitTable();
    }
 private void Initcbbox()
    {
            try {
            cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select * from ChiNhanh");
            rsmd = rs.getMetaData();
            if (rs != null) {
                 model=new DefaultComboBoxModel();
                while (rs.next()) {
                   
                    model.addElement(rs.getString(1));
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (Exception ex) {
            Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbMaCN.setModel(model);
    }
  private void InitTable(){
      lbanh.setSize(160, 160);
        vt = new Vector();
        vt.add("MaTX");
        vt.add("TenTX");
        vt.add("SDT");
        vt.add("MaCN");
        mtable = new DefaultTableModel(vt,0);
       
        try {
            cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select * from TaiXe");
            //rsmd = rs.getMetaData();
            if (rs != null) {
                while (rs.next()==true) {
                    vt = new Vector();
                    vt.add(rs.getString(1));
                    vt.add(rs.getString(2));
                    vt.add(rs.getString(3));
                    vt.add(rs.getString(4));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (Exception ex) {
            Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
        }
        tTaixe.setModel(mtable);
    }
  private void labelicon(String hinh){
                try {
                BufferedImage image=ImageIO.read(new File(hinh));
                 ImageIcon icon=new ImageIcon(image.getScaledInstance(160, 160, Image.SCALE_SMOOTH));
            lbanh.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
            }
  }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaTX = new javax.swing.JTextField();
        txtTenTX = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        cbMaCN = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTaixe = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbMaTX = new javax.swing.JRadioButton();
        rbTenTX = new javax.swing.JRadioButton();
        lbMes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbanh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAnh = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setForeground(new java.awt.Color(51, 204, 255));
        setTitle("Tài xe");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/taixe.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã tài xế:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên tài xế:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("số điện thoại:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mã chi nhánh:");

        txtMaTX.setEnabled(false);

        txtTenTX.setEnabled(false);
        txtTenTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTXActionPerformed(evt);
            }
        });

        txtsdt.setEnabled(false);

        cbMaCN.setEnabled(false);

        tTaixe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tTaixe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTaixeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTaixe);

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/add.png"))); // NOI18N
        btnNew.setMnemonic(KeyEvent.VK_N);
        btnNew.setText("Thêm ");
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/Save.jpg"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setEnabled(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/delete.jpg"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/hình ảnh.jpg"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel6.setText("Tìm theo:");

        buttonGroup1.add(rbMaTX);
        rbMaTX.setSelected(true);
        rbMaTX.setText("Mã tài xế");
        rbMaTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaTXActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTenTX);
        rbTenTX.setText("Tên tài xế");
        rbTenTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTenTXActionPerformed(evt);
            }
        });

        lbMes.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lbMes.setForeground(new java.awt.Color(204, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/search.jpg"))); // NOI18N

        lbanh.setPreferredSize(new java.awt.Dimension(180, 144));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Ảnh đại diện");

        btnAnh.setText("Chọn ảnh");
        btnAnh.setEnabled(false);
        btnAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/Reset.jpg"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTenTX)
                                    .addComponent(rbMaTX))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel1))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenTX, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(txtMaTX)
                                            .addComponent(txtsdt)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAnh)
                                    .addComponent(btnReset)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit)
                                    .addComponent(btnSave)))
                            .addComponent(btnDel))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMaTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTenTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(cbMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNew)
                            .addComponent(btnSave)
                            .addComponent(btnAnh, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset)
                            .addComponent(btnDel)
                            .addComponent(btnEdit)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(rbMaTX)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTenTX)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        edit = 0;
        txtMaTX.setEnabled(true);
        txtTenTX.setEnabled(true);
        txtsdt.setEnabled(true);
        cbMaCN.setEnabled(true);
        btnNew.setEnabled(false);
        btnSave.setEnabled(true);
        btnAnh.setEnabled(true);
        txtMaTX.setText("");
        txtTenTX.setText("");
        txtsdt.setText("");
        lbanh.setIcon(null);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        MaTX = txtMaTX.getText();
        TenTX = txtTenTX.getText();
        sdt = txtsdt.getText();
        MaCN = (String) cbMaCN.getSelectedItem();
        if (MaTX.equals("") || TenTX.equals("") || sdt.equals("") || MaCN.equals("")) {
            lbMes.setText("yeu cau dien day du thong tin");
            return;
        }
        if (edit == 0) {
                    try {
                cnDB=new Connect_Var();
                rs=cnDB.s.executeQuery("select MaTX from TaiXe where MaTX='"+MaTX+"'");
                if(rs.next()==true)
                {
                    lbMes.setText("Ma tai xe da co roi"); 
                    txtMaTX.requestFocus();
                    return;
                }
                 cnDB.s.close();
                    cnDB.cn.close();
            } catch (Exception ex) {
                Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
            }
            int m = JOptionPane.showConfirmDialog(this, "ban co muon luu hay khong", "save", JOptionPane.YES_NO_OPTION);
            if (m == 0) {
               
                try {
                    cnDB=new Connect_Var();
                    String insertsql="insert into TaiXe values('"+MaTX+"','"+TenTX+"','"+sdt+"','"+MaCN+"','"+imagepath+"')";
                    cnDB.SQL(insertsql);
                    vt = new Vector();
                    vt.add(MaTX);
                    vt.add(TenTX);
                    vt.add(sdt);
                    vt.add(MaCN);
                    mtable.addRow(vt);
                    JOptionPane.showMessageDialog(this, "ban da luu thanh cong");
                } catch (Exception ex) {
                    Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } else {
            int m = JOptionPane.showConfirmDialog(this, "ban chac chan muon thay doi", "save", JOptionPane.YES_NO_OPTION);
            if (m == 0) {
                try {
                    cnDB=new Connect_Var();
                    String updatesql="update TaiXe set MaCN='"+MaCN+"',TenTX='"+TenTX+"',SDT='"+sdt+"',Hinh='"+imagepath+"' where MaTX='"+MaTX+"'";
                    cnDB.SQL(updatesql);
                    mtable.setValueAt(MaTX, n, 0);
                    mtable.setValueAt(TenTX, n, 1);
                    mtable.setValueAt( sdt, n, 2);
                    mtable.setValueAt(MaCN, n, 3);
               
                    JOptionPane.showMessageDialog(this, "ban da luu thanh cong");
                } catch (Exception ex) {
                    Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        lbMes.setText("");
        txtMaTX.setEnabled(false);
        txtTenTX.setEnabled(false);
        txtsdt.setEnabled(false);
        cbMaCN.setEnabled(false);
        btnNew.setEnabled(true);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
        btnAnh.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
                if (n == -1) {
            lbMes.setText("BAN CHUA CHON THONG TIN CAN XOA");
        } else {
            int m;
            m = JOptionPane.showConfirmDialog(this, "ban co chac muon xoa khong", "delete", JOptionPane.OK_CANCEL_OPTION);
            if (m == 0) {
                try {
                    cnDB=new Connect_Var();
                    String deletesql="delete from TaiXe where MaTX ='"+String.valueOf(tTaixe.getValueAt(n, 0))+"'";
                    cnDB.SQL(deletesql);
                    cnDB.s.close();
                    cnDB.cn.close();
                } catch (Exception ex) {
                    Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
                }
                mtable.removeRow(n);
                txtMaTX.setText("");
                txtTenTX.setText("");
                txtsdt.setText("");
                lbanh.setIcon(null);
                btnAnh.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void tTaixeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTaixeMouseClicked
        n = tTaixe.getSelectedRow(); 
        //if (n != -1) {
            txtMaTX.setText(String.valueOf(tTaixe.getValueAt(n, 0)));
            txtTenTX.setText(String.valueOf(tTaixe.getValueAt(n, 1)));
            txtsdt.setText(String.valueOf(tTaixe.getValueAt(n, 2)));
            cbMaCN.setSelectedItem(String.valueOf(tTaixe.getValueAt(n, 3)));
            try {
                cnDB=new Connect_Var();
                rs=cnDB.s.executeQuery("select Hinh from TaiXe where MaTX='"+String.valueOf(tTaixe.getValueAt(n, 0))+"'");
                while(rs.next())
                imagepath=rs.getString(1);
                 cnDB.s.close();
                    cnDB.cn.close();
            } catch (Exception ex) {
                Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
            }
            labelicon(imagepath);
        //}
    }//GEN-LAST:event_tTaixeMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        edit = 1;
        if (n == -1) {
            lbMes.setText("BAN CHUA CHON THONG TIN CAN SUA");
        } else {
            txtTenTX.setEnabled(true);
            txtsdt.setEnabled(true);
            cbMaCN.setEnabled(true);
            btnSave.setEnabled(true);
            btnEdit.setEnabled(false);
            btnAnh.setEnabled(true);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
         while (mtable.getRowCount() >0) 
            mtable.removeRow(0);
        if (rbMaTX.isSelected()) {
            try {
                cnDB = new Connect_Var();
                rs = cnDB.s.executeQuery("select* from TaiXe where MaTX like '%" + txtSearch.getText() + "%' ");

            } catch (Exception ex) {
                Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                cnDB = new Connect_Var();
                rs = cnDB.s.executeQuery("select* from TaiXe where TenTX like '%" + txtSearch.getText() + "%' ");
            } catch (Exception ex) {
                Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        try {
            if (rs != null) {
                while (rs.next()) {
                    vt = new Vector();
                    vt.add(rs.getString(1));
                    vt.add(rs.getString(2));
                    vt.add(rs.getString(3));
                    vt.add(rs.getString(4));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Taixe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtTenTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTXActionPerformed

    private void rbTenTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTenTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTenTXActionPerformed

    private void btnAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhActionPerformed
        JFileChooser fc=new JFileChooser();
           if (evt.getSource() == btnAnh) {
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            imagepath=file.getPath();
            labelicon(imagepath);
            //This is where a real application would open the file.
            //log.append("Opening: " + file.getName() + "." + newline);
        } else {
           // log.append("Open command cancelled by user." + newline);
        }
     }
    }//GEN-LAST:event_btnAnhActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtMaTX.setEnabled(false);
        txtTenTX.setEnabled(false);
        txtsdt.setEnabled(false);
        cbMaCN.setEnabled(false);
        btnNew.setEnabled(true);
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
        btnAnh.setEnabled(false);
        Initcbbox();
        txtMaTX.setText("");
        txtTenTX.setText("");
        txtsdt.setText("");
        lbanh.setIcon(null); 
        lbMes.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void rbMaTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaTXActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnh;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbMaCN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbanh;
    private javax.swing.JRadioButton rbMaTX;
    private javax.swing.JRadioButton rbTenTX;
    private javax.swing.JTable tTaixe;
    private javax.swing.JTextField txtMaTX;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenTX;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
