
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Teo
 */
public class Thanhpho extends javax.swing.JInternalFrame {

    /**
     * Creates new form Thanhpho
     */
    private Connect_Var cnDB;
    private DefaultTableModel mtable;
    private DefaultComboBoxModel model;
    private ResultSet rs;
    private ResultSetMetaData rsmd;
    private Vector vt;
    private int n = -1;
    private String  TenTP, MaTP;
    public Thanhpho() {
        initComponents();
        InitTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void InitTable(){
        vt = new Vector();
        vt.add("MaTP");
        vt.add("TenTP");
        mtable = new DefaultTableModel(vt,0);
        //tXe.setModel(mtable);
        try {
            cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select * from Thanhpho");
            rsmd = rs.getMetaData();
            if (rs != null) {
                while (rs.next()) {
                    vt = new Vector();
                    vt.add(rs.getString(1));
                    vt.add(rs.getString(2));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (Exception ex) {
            Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
        }
        tThanhpho.setModel(mtable);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tThanhpho = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaTP = new javax.swing.JTextField();
        txtTenTP = new javax.swing.JTextField();
        lbMes = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/thành phố.jpg"))); // NOI18N

        tThanhpho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tThanhpho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tThanhpho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tThanhphoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tThanhpho);

        jLabel1.setText("Mã Thành Phố");

        jLabel2.setText("Tên Thành Phố");

        txtMaTP.setEnabled(false);

        txtTenTP.setEnabled(false);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel4.setText("Tìm theo tên Thành Phố");

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/add.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/Save.jpg"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setEnabled(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/delete.jpg"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNew)
                                    .addComponent(jLabel2))
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenTP)
                                    .addComponent(txtMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(lbMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnDel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(lbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTenTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(btnNew)
                            .addComponent(btnDel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
         while (mtable.getRowCount() >0) 
        mtable.removeRow(0);
        try {
             cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select* from Thanhpho where TenTP like '%" + txtSearch.getText() + "%' ");

         } catch (Exception ex) {
              Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
            rsmd = rs.getMetaData();
            if (rs != null) {
                while (rs.next()) {
                    vt = new Vector();
                    vt.add(rs.getString(1));
                    vt.add(rs.getString(2));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        MaTP = txtMaTP.getText();
        TenTP = txtTenTP.getText();
        if (MaTP.equals("") || TenTP.equals("")) {
            lbMes.setText("yeu cau dien day du thong tin");
            return;
        }
            int m = JOptionPane.showConfirmDialog(this, "ban co muon luu hay khong", "save", JOptionPane.YES_NO_OPTION);
            if (m == 0) {
               
                try {
                    cnDB=new Connect_Var();
                    String insertsql="insert into Thanhpho values('"+MaTP+"','"+TenTP+"')";
                    cnDB.SQL(insertsql);
                    vt = new Vector();
                    vt.add(MaTP);
                    vt.add(TenTP);
                    mtable.addRow(vt);
                    JOptionPane.showMessageDialog(this, "ban da luu thanh cong");
                } catch (Exception ex) {
                    Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        lbMes.setText("");
        txtMaTP.setEnabled(false);
        txtTenTP.setEnabled(false);
        btnNew.setEnabled(true);
        btnSave.setEnabled(false);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tThanhphoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tThanhphoMouseClicked
        n = tThanhpho.getSelectedRow(); 
        if (n != -1) {
            txtMaTP.setText(String.valueOf(tThanhpho.getValueAt(n, 0)));
            txtTenTP.setText(String.valueOf(tThanhpho.getValueAt(n, 1)));
        }
    }//GEN-LAST:event_tThanhphoMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtMaTP.setEnabled(true);
        txtTenTP.setEnabled(true);
        btnNew.setEnabled(false);
        btnSave.setEnabled(true);
        txtMaTP.setText("");
        txtTenTP.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        if (n == -1) {
            lbMes.setText("BAN CHUA CHON THONG TIN CAN XOA");
        } else {
            int m;
            m = JOptionPane.showConfirmDialog(this, "các thư liên quan sẽ bị xoá, bạn có chắc muốn xóa không", "delete", JOptionPane.OK_CANCEL_OPTION);
             lbMes.setText("");
            if (m == 0) {
                try {
                    cnDB=new Connect_Var();
                    String deletesql="delete from Thanhpho where MaTP ='"+String.valueOf(tThanhpho.getValueAt(n, 0))+"'";
                    cnDB.SQL(deletesql);
                } catch (Exception ex) {
                    Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
                }
                mtable.removeRow(n);
                txtMaTP.setText("");
                txtTenTP.setText("");
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
                 while (mtable.getRowCount() >0) 
        mtable.removeRow(0);
        try {
             cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select* from Thanhpho where TenTP like '%" + txtSearch.getText() + "%' ");

         } catch (Exception ex) {
              Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
            rsmd = rs.getMetaData();
            if (rs != null) {
                while (rs.next()) {
                    vt = new Vector();
                    vt.add(rs.getString(1));
                    vt.add(rs.getString(2));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Thanhpho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMes;
    private javax.swing.JTable tThanhpho;
    private javax.swing.JTextField txtMaTP;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenTP;
    // End of variables declaration//GEN-END:variables
}
