
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Teo
 */
public class Thongtinxe extends javax.swing.JInternalFrame {

     private Connect_Var cnDB;
    private DefaultTableModel mtable;
    private DefaultComboBoxModel model;
    private ResultSet rs;
    private ResultSetMetaData rsmd;
    private Vector vt;
    private int n = -1, edit, Soghe;
    private String Hieuxe, MaCN, Soxe;

    public Thongtinxe() {
        initComponents();
        Initcbbox();
        InitTable();
        
        //System.out.print(n);
    }
    private void Initcbbox()
    {
            try {
            cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select * from ChiNhanh");
            rsmd = rs.getMetaData();
            if (rs != null) {
                 model=new DefaultComboBoxModel();
                while (rs.next()) {
                   
                    model.addElement(rs.getString(1));
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (Exception ex) {
            Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbMaCN.setModel(model);
    }
    private void InitTable(){
        vt = new Vector();
        vt.add("Soxe");
        vt.add("Hieuxe");
        vt.add("Chongoi");
        vt.add("MaCN");
        mtable = new DefaultTableModel(vt,0);
        //tXe.setModel(mtable);
        try {
            cnDB = new Connect_Var();
            rs = cnDB.s.executeQuery("select * from Xe");
            rsmd = rs.getMetaData();
            if (rs != null) {
                while (rs.next()) {
                    vt = new Vector();
                    vt.add(rs.getString(1).toString());
                    vt.add(rs.getString(2));
                    vt.add(rs.getInt(3));
                    vt.add(rs.getString(4));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (Exception ex) {
            Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
        }
        tXe.setModel(mtable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tXe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        txtSoxe = new javax.swing.JTextField();
        txtHieuxe = new javax.swing.JTextField();
        txtSoghe = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbSoxe = new javax.swing.JRadioButton();
        rbHieuxe = new javax.swing.JRadioButton();
        cbMaCN = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::Thông tin xe::");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/images.jpg"))); // NOI18N

        tXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tXe);

        jLabel1.setText("Số xe:");

        jLabel2.setText("Hiệu xe:");

        jLabel3.setText("Số Chỗ Ngồi:");

        jLabel4.setText("Mã Chi Nhánh:");

        lbMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMes.setForeground(new java.awt.Color(255, 0, 0));

        txtSoxe.setEnabled(false);

        txtHieuxe.setEnabled(false);

        txtSoghe.setEnabled(false);

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/add.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/Save.jpg"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setEnabled(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/delete.jpg"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/hình ảnh.jpg"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel6.setText("Tìm Theo:");

        buttonGroup1.add(rbSoxe);
        rbSoxe.setSelected(true);
        rbSoxe.setText("Số xe");

        buttonGroup1.add(rbHieuxe);
        rbHieuxe.setText("Hiệu xe");
        rbHieuxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHieuxeActionPerformed(evt);
            }
        });

        cbMaCN.setEnabled(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/search.jpg"))); // NOI18N

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/Reset.jpg"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSoxe)
                        .addGap(18, 18, 18)
                        .addComponent(rbHieuxe))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoxe)
                            .addComponent(txtHieuxe)
                            .addComponent(txtSoghe)
                            .addComponent(cbMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDel))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReset)))
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbSoxe)
                            .addComponent(rbHieuxe))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSoxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtHieuxe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoghe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(lbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNew)
                            .addComponent(btnSave)
                            .addComponent(btnReset))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit)
                            .addComponent(btnDel))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbHieuxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHieuxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHieuxeActionPerformed

    private void tXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tXeMouseClicked
                n = tXe.getSelectedRow(); 
        if (n != -1) {
            txtSoxe.setText(String.valueOf(tXe.getValueAt(n, 0)));
            txtHieuxe.setText(String.valueOf(tXe.getValueAt(n, 1)));
            txtSoghe.setText(String.valueOf(tXe.getValueAt(n, 2)));
            cbMaCN.setSelectedItem(String.valueOf(tXe.getValueAt(n, 3)));
        }
    }//GEN-LAST:event_tXeMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        edit = 0;
        txtSoxe.setEnabled(true);
        txtHieuxe.setEnabled(true);
        txtSoghe.setEnabled(true);
        cbMaCN.setEnabled(true);
        btnNew.setEnabled(false);
        btnSave.setEnabled(true);
        txtSoxe.setText("");
        txtHieuxe.setText("");
        txtSoghe.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Soxe = txtSoxe.getText();
        Hieuxe = txtHieuxe.getText();
        try {
            Soghe = Integer.parseInt(txtSoghe.getText());
        } catch (NumberFormatException e) {
            lbMes.setText("SO GHE PHAI LA SO NGUYEN");
            txtSoghe.requestFocus();
            return;
        }
        MaCN =  (String) cbMaCN.getSelectedItem();
        if (Soxe.equals("") || Hieuxe.equals("") || Soghe < 1 || MaCN.equals("")) {
            lbMes.setText("yeu cau dien day du thong tin");
            return;
        }
        if (edit == 0) {
            int m = JOptionPane.showConfirmDialog(this, "ban co muon luu hay khong", "save", JOptionPane.YES_NO_OPTION);
            if (m == 0) {
               
                try {
                    cnDB=new Connect_Var();
                    String insertsql="insert into Xe values('"+Soxe+"','"+Hieuxe+"',"+Soghe+",'"+MaCN+"')";
                    cnDB.SQL(insertsql);
                    vt = new Vector();
                    vt.add(Soxe);
                    vt.add(Hieuxe);
                    vt.add(Soghe);
                    vt.add(MaCN);
                    mtable.addRow(vt);
                    JOptionPane.showMessageDialog(this, "ban da luu thanh cong");
                } catch (Exception ex) {
                    Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } else {
            int m = JOptionPane.showConfirmDialog(this, "ban chac chan muon thay doi", "save", JOptionPane.YES_NO_OPTION);
            if (m == 0) {
                try {
                    cnDB=new Connect_Var();
                    String updatesql="update Xe set MaCN='"+MaCN+"',Hieuxe='"+Hieuxe+"',Sochongoi="+Soghe+" where Soxe='"+Soxe+"'";
                    cnDB.SQL(updatesql);
                    mtable.setValueAt(Soxe, n, 0);
                    mtable.setValueAt(Hieuxe, n, 1);
                    mtable.setValueAt( Soghe, n, 2);
                    mtable.setValueAt(MaCN, n, 3);
                    JOptionPane.showMessageDialog(this, "ban da luu thanh cong");
                } catch (Exception ex) {
                    Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        lbMes.setText("");
        txtSoxe.setEnabled(false);
        txtHieuxe.setEnabled(false);
        txtSoghe.setEnabled(false);
        cbMaCN.setEnabled(false);
        btnNew.setEnabled(true);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
                if (n == -1) {
            lbMes.setText("BAN CHUA CHON THONG TIN CAN XOA");
        } else {
            int m;
            m = JOptionPane.showConfirmDialog(this, "ban co chac muon xoa khong", "delete", JOptionPane.OK_CANCEL_OPTION);
            if (m == 0) {
                try {
                     cnDB=new Connect_Var();
                    String deletesql="delete from Xe where Soxe='"+String.valueOf(tXe.getValueAt(n, 0))+"'";
                    cnDB.SQL(deletesql);
                } catch (Exception ex) {
                    Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
                }
                mtable.removeRow(n);
                txtSoxe.setText("");
                txtHieuxe.setText("");
                txtSoghe.setText("");
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        edit = 1;
        if (n == -1) {
            lbMes.setText("BAN CHUA CHON THONG TIN CAN SUA");
        } else {
            txtHieuxe.setEnabled(true);
            txtSoghe.setEnabled(true);
            cbMaCN.setEnabled(true);
            btnSave.setEnabled(true);
            btnEdit.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        while (mtable.getRowCount() >0) 
            mtable.removeRow(0);
        if (rbSoxe.isSelected()) {
            try {
                cnDB = new Connect_Var();
                rs = cnDB.s.executeQuery("select* from Xe where Soxe like '%" + txtSearch.getText() + "%' ");

            } catch (Exception ex) {
                Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                cnDB = new Connect_Var();
                rs = cnDB.s.executeQuery("select* from Xe where Hieuxe like '%" + txtSearch.getText() + "%' ");
            } catch (Exception ex) {
                Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        try {
            rsmd = rs.getMetaData();
            if (rs != null) {
                while (rs.next()) {
                    vt = new Vector();
                    vt.add(rs.getString(1));
                    vt.add(rs.getString(2));
                    vt.add(rs.getInt(3));
                    vt.add(rs.getString(4));
                    mtable.addRow(vt);
                }
                rs.close();
                cnDB.s.close();
                cnDB.cn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Thongtinxe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSoxe.setEnabled(false);
        txtHieuxe.setEnabled(false);
        txtSoghe.setEnabled(false);
        cbMaCN.setEnabled(false);
        btnNew.setEnabled(true);
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
        txtSoxe.setText("");
        txtHieuxe.setText("");
        txtSoghe.setText("");
        Initcbbox();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbMaCN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMes;
    private javax.swing.JRadioButton rbHieuxe;
    private javax.swing.JRadioButton rbSoxe;
    private javax.swing.JTable tXe;
    private javax.swing.JTextField txtHieuxe;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoghe;
    private javax.swing.JTextField txtSoxe;
    // End of variables declaration//GEN-END:variables
}
